<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Staff Account</name>
   <tag></tag>
   <elementGuidId>33101168-fa3a-4c02-9f42-dadc4fd1e8e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CodeNinjasExchange</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CodeNinjasExchange']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ea5bf68-e679-4204-825b-a8dec859e2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accountButton firstButton</value>
      <webElementGuid>d89eb3f4-1e86-417a-bfcf-aaa9c8da3432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CodeNinjasExchange</value>
      <webElementGuid>53d7c536-1d6f-4328-b1ab-88d15ceedf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Staff Account</value>
      <webElementGuid>73f5096e-aaa7-4d1e-8629-a493d878506c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CodeNinjasExchange&quot;)</value>
      <webElementGuid>6822d26b-9eff-49df-a429-aa70c40526b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61c2aaeb-c7dc-4412-b0ab-bb275f48c7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accountButton firstButton</value>
      <webElementGuid>418844e2-2554-4855-b26b-45025a7710ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CodeNinjasExchange</value>
      <webElementGuid>1552698f-8ead-4b1d-a876-591e6153d475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Staff Account</value>
      <webElementGuid>3281b514-80dd-4789-b5c5-488ba1589d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CodeNinjasExchange&quot;)</value>
      <webElementGuid>96e3152c-76af-4fd4-b055-557808278076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50fceafa-4c51-494f-b6e9-8f875aafb624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accountButton firstButton</value>
      <webElementGuid>0e69ff55-b234-4b87-9381-80e47c499b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CodeNinjasExchange</value>
      <webElementGuid>e00c10c5-0d0e-4a75-9646-aff78a075675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Staff Account</value>
      <webElementGuid>28e3117e-8956-4f42-89f5-8606fce3f75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CodeNinjasExchange&quot;)</value>
      <webElementGuid>071d4a35-3ae1-40ee-a851-0c24efe5ffbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CodeNinjasExchange']</value>
      <webElementGuid>9f9559b4-dfde-4eb5-a228-85af98dd48ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='api']/div/div[2]/div/button</value>
      <webElementGuid>69737611-7fad-45d7-b7b8-c341eaf45a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in with your social account'])[1]/following::button[1]</value>
      <webElementGuid>a6bd2ac2-4c65-488d-8393-efe319f9cbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'CodeNinjasExchange', '&quot;', ')')])[1]/following::button[1]</value>
      <webElementGuid>4ef320d7-db5b-45e7-8532-be93395d9548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::button[1]</value>
      <webElementGuid>2d253f5e-b51e-4555-8477-cc6c3bc13440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in with your existing account'])[1]/preceding::button[1]</value>
      <webElementGuid>3c4b7a2c-0373-4320-b940-37addb70a502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Staff Account']/parent::*</value>
      <webElementGuid>8272395b-6734-433d-892f-53490e8fdb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f3ebae69-553b-41c5-9531-18980a5a9bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CodeNinjasExchange' and (text() = 'Staff Account' or . = 'Staff Account')]</value>
      <webElementGuid>3d5fab3a-8e96-4e53-9395-bc9db11dfa4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
