<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Manual Scan-In</name>
   <tag></tag>
   <elementGuidId>87dba913-1a67-4df5-97e7-5109d7f0acb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-291-539-panel']/div/div[2]/div/button[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>edb954ca-98be-4601-85cd-3caf3d3debfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>controller.openManualScanIn(member)</value>
      <webElementGuid>c5145f84-68b7-4a76-81c4-129b081b41b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>controller.isLoading</value>
      <webElementGuid>3d718634-f511-4d20-adcf-d9435e28ce5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manual Scan-In</value>
      <webElementGuid>34baa57d-fe25-4bd1-97f6-74acc8143701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-291-539-panel&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;actions ng-scope&quot;]/div[@class=&quot;action-buttons-slim ng-scope&quot;]/button[4]</value>
      <webElementGuid>32cfb227-db27-4d06-bdab-9c984d46c7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da969414-e064-4a16-b0cf-de75af5313e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>controller.openManualScanIn(member)</value>
      <webElementGuid>1767112a-d201-4d15-8bc8-dfd0e8b87668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>controller.isLoading</value>
      <webElementGuid>e26f147c-faf5-410b-bc0e-1db82a6a620e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manual Scan-In</value>
      <webElementGuid>5081abae-394f-4f09-b970-fd9eceee996f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-237-987-panel&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;actions ng-scope&quot;]/div[@class=&quot;action-buttons-slim ng-scope&quot;]/button[4]</value>
      <webElementGuid>9f368116-6eb1-49c5-8808-1eeb85cb1d57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-291-539-panel']/div/div[2]/div/button[4]</value>
      <webElementGuid>d8520655-98d8-4b6c-a3a5-02f6805f9e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belt Progress'])[1]/following::button[1]</value>
      <webElementGuid>f6d95b89-783f-45b4-9810-7a3fb2e2dbc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usage Report'])[1]/following::button[2]</value>
      <webElementGuid>d734ec5a-1b93-42bf-a13c-26e820dcf694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='At-Home Scan-In'])[1]/preceding::button[1]</value>
      <webElementGuid>f95c7d2c-bb41-49bc-bdfb-03cd3a0b5929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign Belt'])[1]/preceding::button[2]</value>
      <webElementGuid>a325222d-fc5c-4405-a165-842ff6c7269e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manual Scan-In']/parent::*</value>
      <webElementGuid>24138118-ad8b-4ca5-99a5-9746f53893aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>bed51be7-4197-4c1d-9360-09f9e6bcb2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Manual Scan-In' or . = 'Manual Scan-In')]</value>
      <webElementGuid>d4887da0-e3a8-45eb-b622-5efd1eb88818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-237-987-panel']/div/div[2]/div/button[4]</value>
      <webElementGuid>9cc33ef8-1ad3-4c3f-8662-e0fad9f83352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
