<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign Out_ng-pristine ng-untouched ng-_427508</name>
   <tag></tag>
   <elementGuidId>d49eea5f-de32-40ac-892d-d4bc5aa714fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c086532-eba4-4fcc-82cf-daf10e870bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05d4dc75-2ed8-4617-af04-09748946c5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>controller.searchTerm</value>
      <webElementGuid>c01cf762-c02a-4ac8-b135-40bf8c8ca57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>controller.search(controller.searchTerm)</value>
      <webElementGuid>250fd2d7-2116-499a-a4a5-13ea2784e454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ debounce: 1000 }</value>
      <webElementGuid>e1564886-8394-462b-8ead-e2ca436471e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by typing or scanning a wristband...</value>
      <webElementGuid>ed8e7cb4-4d6b-4662-bb5b-8ee94d741005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>f9e3d182-f064-40ba-9613-0137e19dbf97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope wf-azosansweb-n7-active wf-azosansweb-i7-active wf-azosansweb-i4-active wf-azosansweb-n4-active wf-active&quot;]/body[@class=&quot;bg&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;customer-search ng-scope&quot;]/div[@class=&quot;search-bar container&quot;]/div[@class=&quot;search-input&quot;]/div[@class=&quot;wrapper&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>f7fe383a-bf82-44e3-9b7b-95d1401824e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b75f029-dfa4-408e-b999-eecf0f5097b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ecf30b6f-7d48-4257-8ffa-ac21a85aa545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>controller.searchTerm</value>
      <webElementGuid>92f4cc52-f179-4f1d-a03c-b1bed7179816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>controller.search(controller.searchTerm)</value>
      <webElementGuid>c1850c9d-b110-423e-9df0-3f3aa3ef8f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ debounce: 1000 }</value>
      <webElementGuid>763d1cc8-7034-4585-bea1-75f32d922363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by typing or scanning a wristband...</value>
      <webElementGuid>6d20f5e1-e0db-449a-99c2-2f487ded17a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>57efb8c1-43d4-4707-833d-3cd4236326f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope wf-azosansweb-n7-inactive wf-azosansweb-i7-inactive wf-azosansweb-i4-inactive wf-azosansweb-n4-inactive wf-inactive&quot;]/body[@class=&quot;bg&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;customer-search ng-scope&quot;]/div[@class=&quot;search-bar container&quot;]/div[@class=&quot;search-input&quot;]/div[@class=&quot;wrapper&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>fdb7064e-3b19-427d-a72e-f784de97afa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>2796a91b-d0b3-434e-998c-624cd8f7346a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e22eac1e-0ddf-433b-81c0-767944bf6fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search by typing or scanning a wristband...']</value>
      <webElementGuid>c46f613a-0dd7-4d82-a7cb-56efaba42f1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
